### ISSUE TITLE
extraResources not work

### ISSUE THREAD

**Issue by MBearo** [nklayman/vue-cli-plugin-electron-builder#1259]
**Describe the bug**
extraResources not work.
https://github.com/MBearo/test-extra-resources
```javascript
//vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true,
      extraResources: ['icon']
    }
  }
}
```
set DEBUG=electron-builder,I see some log
```
effective config  config=
                        directories:
                          output: dist_electron
                          buildResources: build
                          app: dist_electron/bundled
                        files:
                          - filter:
                              - '**'
                        extends: null
```
if I use electron-build,same config
```
effective config  config=
                        directories:
                          output: dist
                          buildResources: build
                        extraResources:
                          - filter:
                              - icon
```

**To Reproduce**
```
vue create project
vue add electron-builder
```
or this repository

**Expected behavior**
There is a `icon` folder under the `dist_electron/mac/test-extra-resources.app/Contents/Resources`

**Screenshots**

**Environment (please complete the following information):**
https://github.com/MBearo/test-extra-resources

**Additional context**
@vue/cli 4.5.9
vue-cli-plugin-electron-builder 2.0.0-rc.6
