### ISSUE TITLE
Not respecting build targets even though listed in builder-effective-config

### ISSUE THREAD

**Issue by envision** [nklayman/vue-cli-plugin-electron-builder#197]
Electron is bundling for Mac and only for Mac, even though build options do not include a Mac target but only a single Windows target.

While the autogenerated `builder-effective-config.yaml` is reflecting the build options correctly:

```
directories:
  output: dist_electron
  buildResources: build
  app: dist_electron/bundled
files:
  - filter:
      - dist_electron/**/*
      - src/background.js
      - background.js
extends: null
asar: true
appId: com.XXX
productName: XXX
win:
  target:
    - nsis
  icon: build/icons/icon.ico
electronVersion: 4.0.5
```

Output getting from CLI:
```
 INFO  Building app with electron-builder:
  • electron-builder version=20.38.5
  • writing effective config file=dist_electron/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=darwin arch=x64 electron=4.0.5 appOutDir=dist_electron/mac
  • skipped macOS application code signing reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=
0 identities found
Valid identities only
0 valid identities found
  • building        target=macOS zip arch=x64 file=dist_electron/XXX-0.1.0-mac.zip
  • building        target=DMG arch=x64 file=dist_electron/XXX-0.1.0.dmg
  • building block map blockMapFile=dist_electron/XXX-0.1.0.dmg.blockmap
  • building embedded block map file=dist_electron/XXX-0.1.0-mac.zip
 DONE  Build complete!
✨  Done in 107.17s.
```

**Environment:**
 - OS and version: macOS Mojave 10.14.3 (18D109)
 - node version: v10.15.0
 - yarn version: 1.13.0
 - vue-cli-plugin-electron-builder version : 1.0.1
 - electron version: 4.0.5
 - other vue plugins used:
```
    "@vue/cli-plugin-babel": "^3.4.0",
    "@vue/cli-plugin-e2e-cypress": "^3.4.0",
    "@vue/cli-plugin-eslint": "^3.4.0",
    "@vue/cli-plugin-pwa": "^3.4.0",
    "@vue/cli-plugin-typescript": "^3.4.0",
    "@vue/cli-plugin-unit-jest": "^3.4.0",
    "@vue/cli-service": "^3.4.0",
    "@vue/eslint-config-standard": "^4.0.0",
    "@vue/eslint-config-typescript": "^4.0.0",
    "@vue/test-utils": "^1.0.0-beta.20",
    "vue-class-component": "^6.3.2",
    "vue-cli-plugin-ant-design": "^1.0.0",
    "vue-cli-plugin-electron-builder": "^1.0.0",
    "vue-mixin-decorator": "^1.1.0",
    "vue-property-decorator": "^7.3.0",
    "vue-template-compiler": "^2.5.21",
    "vuex-class": "^0.3.1"
```
 - custom config for vcp-electron-builder:
```
  pluginOptions: {
    electronBuilder: {
      mainProcessFile: 'background.js',
      builderOptions: {
        asar: true,
        appId: 'com.XXX',
        productName: 'XXX',
        files: [
          'dist_electron/**/*',
          'src/background.js',
          'background.js'
        ],
        win: {
          target: [
            'nsis'
          ],
          icon: 'build/icons/icon.ico'
        }
      }
    }
  }
```
