### ISSUE TITLE
Use GitHub workflow build app, Can not auto update.

### ISSUE THREAD

**Issue by Hunlongyu** [nklayman/vue-cli-plugin-electron-builder#734]
https://github.com/Hunlongyu/p-test

#### 1. Use GitHub workflow build app, Can not auto update.

> .github\workflows\relase.yml ⬇

```yml
name: release-build

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: |
          yarn
          yarn electron:build
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist_electron/*.exe
            dist_electron/*.dmg
            dist_electron/*.snap
            dist_electron/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

> package.json ⬇

```js
"electron:build": "vue-cli-service electron:build",
```

> background.js ⬇

```js
import { autoUpdater } from 'electron-updater'
...
function createWindow () {
  ...
  if (process.env.WEBPACK_DEV_SERVER_URL) {
    win.loadURL(process.env.WEBPACK_DEV_SERVER_URL)
    if (!process.env.IS_TEST) win.webContents.openDevTools()
  } else {
    win.loadURL('app://./index.html')
    autoUpdater.checkForUpdatesAndNotify() // Doesn't seem to work
  }
  ...
}
```

> vue.config.js ⬇

```js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      nodeIntegration: true,
      builderOptions: {
        appId: 'com.electron.ptest',
        nsis: {
          oneClick: false,
          allowToChangeInstallationDirectory: true
        },
        copyright: 'Copyright @ 2020 Hunlongyu',
        productName: 'ptest'
      }
    }
  }
}
```

#### 2. how to build ia32 and x64 app with github workflow.

push release look like:

1. ptest-v1.0.0-x64.exe
2. ptest-v1.0.0-ia32.exe
3. ptest-v1.0.0-x64.dmg
4. ptest-v1.0.0-x64.snap
