### ISSUE TITLE
How To Hide Vertical Scrollbar 

### ISSUE THREAD

**Issue by yehtut-indexzero** [nklayman/vue-cli-plugin-electron-builder#877]
Hi Everyone,

what I am trying to embedded web application in Electron as Kiosk Mode and how to hide vertical scroll bar. Thank you

**Comment by nklayman** [comment]
Just add the following to your `app.vue` in the `<style>` tag:

If you don't want the user to be able to scroll:
```css
html {
  overflow-y: hidden
}
```
If you want the user to still be able to scroll, just hide the scrollbar:
```css
::-webkit-scrollbar {
  width: 0px; /* Remove scrollbar space */
}
```
